version: 2
defaults: &defaults
  working_directory: ~/edufami-webapp
  docker:
    - image: cimg/node:15.4.0
      steps:
        - checkout
        - run: node --version
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-v3-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-v3-{{ arch }}-{{ .Branch }}
            - yarn-cache-v3
      - run: yarn install
      - save_cache:
          key: yarn-cache-v3-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/edufami-webapp/
          paths:
            - node_modules
  prettier-check:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/edufami-webapp
      - run:
          name: Run prettier check
          command: ./node_modules/.bin/prettier-eslint --list-different src/**/*.js

  eslint-check:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/edufami-webapp
      - run:
          name: Run post-install
          command: yarn postinstall
      - run:
          name: Run eslint check
          command: ./node_modules/.bin/eslint src/**/*.js src/**/*.jsx -c ./.eslintrc

workflows:
  version: 2
  commit:
    jobs:
      - build
      - prettier-check:
          requires:
            - build
      - eslint-check:
          requires:
            - build
