version: 2
jobs:
  build:
    working_directory: ~/edufami-webapp
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  prettier-check:
    steps:
      - checkout
      - attach_workspace:
          at: ~/edufami-webapp
      - run:
          name: Run prettier check
          command: yarn prettier

  eslint-check:
    steps:
      - checkout
      - attach_workspace:
          at: ~/edufami-webapp
      - run:
          name: Run eslint check
          command: yarn eslint
