version: 2
defaults: &defaults
  working_directory: ~/edufami-webapp
  docker:
    - image: circleci/ruby:2.7.1-node-browsers
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-v3-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache-v3-{{ arch }}-{{ .Branch }}
            - yarn-cache-v3
      - run: yarn install
      - save_cache:
          key: yarn-cache-v3-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/edufami-webapp/
          paths:
            - node_modules
  prettier-check:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/edufami-webapp
      - run:
          name: Run prettier check
          command: yarn prettier

  eslint-check:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/edufami-webapp
      - run:
          name: Run post-install
          command: yarn postinstall
      - run:
          name: Run eslint check
          command: yarn eslint

workflows:
  version: 2
  commit:
    jobs:
      - build
      - prettier-check:
          requires:
            - build
      - eslint-check:
          requires:
            - build
