version: 2
docker:
  - image: 'miyajan/prettier:1.15.3'
commands:
  prettier_list_different:
    description: |
      Run prettier --list-different over files in the repository.
    parameters:
      ignore_path:
        description: |
          https://prettier.io/docs/en/cli.html#ignore-path
          Path to a file containing patterns that describe files to ignore.
          By default, prettier looks for ./.prettierignore
        type: string
        default: ./.prettierignore
      extension:
        description: |
          Files that have this extension are checked by prettier.
          To specify multiple extensions, use comma separated string. (e.g. yml,yaml)
        type: string
    steps:
      - run:
          name: Run Prettier << parameters.extension >>
          command: prettier --ignore-path '<< parameters.ignore_path >>' --list-different **/*.{<< parameters.extension >>}

executors:
  prettier:
    docker:
      - image: miyajan/prettier:1.15.3
      
jobs:
  build:
    working_directory: ~/edufami-webapp
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  check-javascript:
    description: |
      Run prettier --list-different over any JavaScript files in the repository.
    parameters:
      ignore_path:
        type: string
        default: ./.prettierignore
        description: |
          https://prettier.io/docs/en/cli.html#ignore-path
          Path to a file containing patterns that describe files to ignore.
          By default, prettier looks for ./.prettierignore
    executor: prettier
    steps:
      - checkout
      - prettier_list_different:
          ignore_path: << parameters.ignore_path >>
          extension: js
